import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import Header from "./Header";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  axes: ["opsz", "wdth", "slnt"],
  variable: "--font-roboto-flex",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(robotoFlex.className, "bg-black text-white")}>
        {/* <div className="grain" /> */}

        <Header />
        <main>{props.children}</main>
      </body>
    </html>
  );
}
